'use strict';
const STORAGE_KEY='medicine-notebook.records.v1';
const state={view:'home',selected:null,qrList:[],notice:'',stream:null,scanTimer:null,detector:null};
const app=document.querySelector('#app');
const backButton=document.querySelector('#back-button');
const headerTitle=document.querySelector('#header-title');
const dialog=document.querySelector('#scanner-dialog');
const video=document.querySelector('#camera-video');
const statusText=document.querySelector('#scanner-status');
const toast=document.querySelector('#toast');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function getRecords(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function writeRecords(records){localStorage.setItem(STORAGE_KEY,JSON.stringify(records))}
function norm(s){return String(s||'').replace(/\s+/g,'').trim()}
function score(r){return(r.prescriptionDate?10:0)+(r.hospitalName?10:0)+(r.department?3:0)+(r.doctorName?3:0)+r.medicines.length*20+r.medicines.reduce((n,m)=>n+(m.name?5:0)+m.usage.filter(Boolean).length*2+(m.quantityInfo?3:0),0)}
function saveRecord(record){const records=getRecords();const i=records.findIndex(r=>norm(r.prescriptionDate)===norm(record.prescriptionDate)&&norm(r.hospitalName)===norm(record.hospitalName));if(i>=0){if(score(record)<=score(records[i]))return false;records[i]=record}else records.unshift(record);writeRecords(records);return true}
function flash(message){toast.textContent=message;toast.classList.add('show');clearTimeout(flash.timer);flash.timer=setTimeout(()=>toast.classList.remove('show'),2600)}
function navigate(view,selected=null){state.view=view;state.selected=selected;render();app.focus();scrollTo({top:0,behavior:'smooth'})}
function render(){backButton.classList.toggle('hidden',state.view==='home');headerTitle.textContent=state.view==='home'?'お薬手帳':state.view==='history'?'記録一覧':'お薬の記録';if(state.view==='home')renderHome();else if(state.view==='history')renderHistory();else renderDetail(state.selected)}

function renderHome(){const count=state.qrList.length;app.innerHTML=`<section class="hero"><div class="hero-icon">✚</div><h1>お薬手帳</h1><p>処方箋のQRコードを読み取り、<br>お薬の記録をこの端末に保存します。</p></section>${count?`<div class="summary-card"><strong>✓ ${count}件</strong> のQRコードを読み取りました</div>`:''}<div class="button-stack"><button class="button secondary" data-action="history">▤　記録を見る</button><button class="button ${count?'orange':'primary'}" data-action="scan">▦　${count?'次のQRコードを読む':'QRコードを読み取る'}</button>${count?'<button class="button success wide" data-action="finish">読み取り終了・保存</button>':''}</div>${state.notice?`<div class="notice">${esc(state.notice)}</div>`:''}<div class="utility-row"><button class="button ghost" data-action="export">CSV出力</button><button class="button ghost" data-action="backup">バックアップ</button><label class="button ghost file-button">復元<input id="json-import" type="file" accept="application/json"></label></div><p class="privacy">記録はサーバーへ送信せず、このブラウザ内だけに保存されます。<br>機種変更前にはバックアップを保存してください。</p>`;app.querySelector('[data-action="history"]').onclick=()=>navigate('history');app.querySelector('[data-action="scan"]').onclick=openScanner;app.querySelector('[data-action="finish"]')?.addEventListener('click',finishReading);app.querySelector('[data-action="export"]').onclick=exportCsv;app.querySelector('[data-action="backup"]').onclick=()=>download(JSON.stringify(getRecords(),null,2),'お薬手帳バックアップ.json','application/json');app.querySelector('#json-import').onchange=importJson}
function renderHistory(){const records=getRecords();app.innerHTML=`<h1 class="page-title">記録を見る</h1><p class="page-subtitle">見たい記録を選んでください</p>${records.length?`<div class="record-list">${records.map((r,i)=>`<button class="record-card" data-index="${i}"><div class="record-date">${esc(r.prescriptionDate||'日付なし')}</div><div class="record-hospital">${esc(r.hospitalName||'医療機関名なし')}</div><div class="record-meta">${esc([r.department,r.doctorName&&r.doctorName+' 先生'].filter(Boolean).join('　'))}　お薬 ${r.medicines.length}件</div></button>`).join('')}</div>`:'<div class="empty">保存された記録はまだありません。</div>'}`;app.querySelectorAll('.record-card').forEach(b=>b.onclick=()=>navigate('detail',Number(b.dataset.index)))}
function renderDetail(index){const r=getRecords()[index];if(!r){navigate('history');return}app.innerHTML=`<div class="detail-head"><h1>お薬の記録</h1><div class="hospital">${esc([r.prescriptionDate,r.hospitalName].filter(Boolean).join('　'))}</div><p>${esc([r.department,r.doctorName&&r.doctorName+' 先生'].filter(Boolean).join('　'))}</p></div><div class="medicine-list">${r.medicines.map(m=>`<article class="medicine"><h2>${esc(m.name)}</h2>${m.usage.map(u=>`<p>${esc(u)}</p>`).join('')}${m.quantityInfo?`<p class="quantity">${esc(m.quantityInfo)}</p>`:''}</article>`).join('')}</div><div class="bottom-actions"><button class="button secondary" data-action="back">記録一覧へ戻る</button><button class="button ghost danger" data-action="delete">この記録を削除</button></div>`;app.querySelector('[data-action="back"]').onclick=()=>navigate('history');app.querySelector('[data-action="delete"]').onclick=()=>{if(confirm('このお薬の記録を削除しますか？')){const records=getRecords();records.splice(index,1);writeRecords(records);flash('記録を削除しました');navigate('history')}}}

function normalizeQrData(data){return String(data||'').replace(/\r\n?/g,'\n').split('\n').map(s=>s.trim()).filter(Boolean).join('\n').trim()}
function addQrData(raw){const data=normalizeQrData(raw);if(!data)return'EMPTY';if(!state.qrList.length&&!data.split('\n').some(l=>l.trimStart().startsWith('51,')))return'MISSING';if(state.qrList.some(q=>norm(q)===norm(data)))return'DUPLICATE';state.qrList.push(data);state.notice='';return'ADDED'}
function acceptQr(raw){const result=addQrData(raw);if(result==='ADDED'){closeScanner();flash(`QRコードを${state.qrList.length}件読み取りました`);render()}else if(result==='MISSING')statusText.textContent='最初のQRコードではありません。病院名を含む1枚目から読み取ってください。';else if(result==='DUPLICATE')statusText.textContent='このQRコードはすでに読み取り済みです。';else statusText.textContent='読み取りデータが空です。'}

async function openScanner(){dialog.showModal();document.querySelector('#paste-panel').classList.add('hidden');statusText.textContent='カメラを起動しています…';if(!('BarcodeDetector'in window)){statusText.textContent='このブラウザはカメラのQR読取に対応していません。画像選択または貼り付けをご利用ください。';return}try{state.detector=new BarcodeDetector({formats:['qr_code']});state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280}},audio:false});video.srcObject=state.stream;await video.play();statusText.textContent='QRコードを枠内に映してください';scanFrame()}catch(e){statusText.textContent=location.protocol==='https:'?'カメラを使用できません。権限設定をご確認ください。':'カメラ利用にはHTTPSでの公開が必要です。画像選択をご利用ください。'}}
async function scanFrame(){if(!state.stream||dialog.open===false)return;try{const codes=await state.detector.detect(video);if(codes[0]?.rawValue){acceptQr(codes[0].rawValue);return}}catch{}state.scanTimer=setTimeout(scanFrame,180)}
function closeScanner(){clearTimeout(state.scanTimer);state.scanTimer=null;state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;video.srcObject=null;if(dialog.open)dialog.close()}
async function scanImage(file){if(!file)return;if(!('BarcodeDetector'in window)){statusText.textContent='このブラウザでは画像解析に対応していません。文字データの貼り付けをご利用ください。';return}try{statusText.textContent='画像を解析しています…';const bitmap=await createImageBitmap(file);const detector=state.detector||new BarcodeDetector({formats:['qr_code']});const codes=await detector.detect(bitmap);bitmap.close();codes[0]?.rawValue?acceptQr(codes[0].rawValue):statusText.textContent='画像からQRコードを見つけられませんでした。'}catch{statusText.textContent='画像を読み取れませんでした。'}}

function parsePrescription(data){const lines=rebuildLines(data);let prescriptionDate='',hospitalName='',department='',doctorName='';const map=new Map();const get=n=>{if(!map.has(n))map.set(n,{name:'',usage:[],medicineQuantity:'',dispensingQuantity:''});return map.get(n)};for(const line of lines){const p=line.split(',').map(x=>x.trim());if(p[0]==='5')prescriptionDate=formatDate(p[1]||'');else if(p[0]==='51')hospitalName=p[1]||'';else if(p[0]==='55'){doctorName=display(p[1]||'');department=display((p[2]||'').replace(/^【|】$/g,''))}else if(p[0]==='201'){const n=Number.parseInt(p[1],10);if(Number.isNaN(n))continue;const d=get(n);if(p[2])d.name=display(p[2]);if(p[3]&&p[4])d.medicineQuantity=number(p[3])+display(p[4])}else if(p[0]==='301'){const n=Number.parseInt(p[1],10);if(Number.isNaN(n))continue;const d=get(n),u=display(p[2]||'');if(u&&!d.usage.includes(u))d.usage.push(u);if(p[3]&&p[4])d.dispensingQuantity=number(p[3])+display(p[4])}else if(p[0]==='311'){const n=Number.parseInt(p[1],10);if(Number.isNaN(n))continue;const d=get(n),u=display(p[2]||'');if(u&&!d.usage.includes(u))d.usage.push(u)}}const medicines=[...map.entries()].sort((a,b)=>a[0]-b[0]).map(([,d])=>({name:d.name.trim(),usage:d.usage,quantityInfo:d.dispensingQuantity.endsWith('日分')?d.dispensingQuantity:(d.medicineQuantity||d.dispensingQuantity)})).filter(m=>m.name);return{prescriptionDate,hospitalName,department,doctorName,medicines}}
function rebuildLines(data){const codes=new Set(['1','2','3','4','5','11','15','31','51','55','201','281','291','301','311','391','401','411','421','501','601','701','911']);const out=[];for(const line of normalizeQrData(data).split('\n')){if(codes.has(line.split(',')[0].trim()))out.push(line);else if(out.length)out[out.length-1]+=line;else out.push(line)}return out}
function display(v){return String(v).replaceAll('﨑','崎').replaceAll('髙','高').replaceAll('神','神').replaceAll('塚','塚').trim()}
function number(v){const n=String(v).trim().replace(/[０-９]/g,c=>String(c.charCodeAt(0)-65248)).replaceAll('．','.');const x=Number(n);return Number.isFinite(x)?String(x):n}
function formatDate(v){if(!/^\d{8}$/.test(v))return v;const y=+v.slice(0,4),m=+v.slice(4,6),d=+v.slice(6,8),dt=new Date(y,m-1,d);return dt.getFullYear()===y&&dt.getMonth()===m-1&&dt.getDate()===d?`${y}年${m}月${d}日`:v}
function finishReading(){const record=parsePrescription(state.qrList.join('\n'));if(!record.medicines.length){state.notice='お薬の情報を読み取れませんでした。QRコードをご確認ください。';render();return}const count=state.qrList.length;const saved=saveRecord(record);state.qrList=[];state.notice='';flash(saved?'記録を保存しました':'同じ処方の記録がすでにあります');navigate('detail',getRecords().findIndex(r=>norm(r.prescriptionDate)===norm(record.prescriptionDate)&&norm(r.hospitalName)===norm(record.hospitalName)));}

function csvCell(v){return'"'+String(v??'').replaceAll('"','""')+'"'}
function exportCsv(){const records=getRecords();if(!records.length){flash('出力する記録がありません');return}const rows=[['処方日','医療機関','診療科','医師名','薬品名','用法','数量']];for(const r of records)for(const m of r.medicines)rows.push([r.prescriptionDate,r.hospitalName,r.department,r.doctorName,m.name,m.usage.join(' / '),m.quantityInfo]);download('\ufeff'+rows.map(row=>row.map(csvCell).join(',')).join('\r\n'),'お薬手帳.csv','text/csv;charset=utf-8')}
function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importJson(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data))throw 0;if(confirm(`${data.length}件の記録を読み込み、現在の記録と統合しますか？`)){for(const r of data)if(r&&Array.isArray(r.medicines))saveRecord(r);flash('記録を読み込みました');render()}}catch{flash('JSONファイルの形式が正しくありません')}};reader.readAsText(file)}

backButton.onclick=()=>state.view==='detail'?navigate('history'):navigate('home');
document.querySelector('#close-scanner').onclick=closeScanner;
document.querySelector('#show-paste').onclick=()=>document.querySelector('#paste-panel').classList.toggle('hidden');
document.querySelector('#add-qr-text').onclick=()=>acceptQr(document.querySelector('#qr-text').value);
document.querySelector('#qr-image').onchange=e=>scanImage(e.target.files[0]);
dialog.addEventListener('cancel',e=>{e.preventDefault();closeScanner()});
let installPrompt=null;const installButton=document.querySelector('#install-button');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;installButton.classList.remove('hidden')});installButton.onclick=async()=>{await installPrompt?.prompt();installPrompt=null;installButton.classList.add('hidden')};
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
